alias ls="ls -G"
alias beep="echo -en '\007'"
alias tmux="TERM=xterm-256color tmux"
alias devkill="tmux kill-session -t dev"
alias ack="ack-grep"

# Runs the specs of a project, or a file referred to by FILE_TO_TEST
function spec_test { bundle exec rspec $FILE_TO_TEST -c || beep; }

. ~/.local_bashrc
