alias ls="ls -G --color=always"
alias beep="echo -en '\007'"
alias tmux="TERM=xterm-256color tmux"
alias devkill="tmux kill-session -t dev"
alias ack="ack-grep"
alias checkstyle="java -jar /lib/checkstyle/checkstyle-7.1.1-all.jar -c /etc/checkstyle/google_checks.xml"

# Runs the specs of a project, or a file referred to by FILE_TO_TEST
function spec_test { bundle exec rspec $FILE_TO_TEST -c || beep; }

. ~/.local_bashrc
